{
 "title": "Kong Dashboard by C3t4r4 V7",
 "tags": [ "C3t4r4" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "job",
    "query": {
     "query": "label_values(kong_http_requests_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kong_nginx_connections_total{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(kong_http_requests_total{job=~\"$job\"},service)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(kong_http_requests_total{job=~\"$job\"},route)"
    }
   },
   {
    "name": "upstream",
    "query": {
     "query": "label_values(kong_upstream_target_health{job=~\"$job\"},upstream)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy status ($job)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "repeat": "job",
   "targets": [
    {
     "expr": "sum(kong_upstream_target_health{state=\"healthy\", job=~\"$job\", upstream=~\"$upstream\"}) by (job, route, upstream, target, address) * -1  + sum(kong_upstream_target_health{state=~\"(unhealthy|dns_error)\", job=~\"$job\", upstream=~\"$upstream\"}) by (job, route, upstream, target, address)",
     "legendFormat": "{{upstream}}:{{target}}"
    }
   ]
  },
  {
   "title": "Upstream Status ($job)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "repeat": "job",
   "targets": [
    {
     "expr": "sum(\n# map state to a numeric value\n# since grafana doesn't support value mapping yet\n  label_replace(\n    label_replace(\n      label_replace(\n       kong_upstream_target_health{ job=~\"$job\", upstream=~\"$upstream\"}\n       # healthy is positive number\n       , \"state_value\", \"1\", \"state\", \"healthy\"\n       # healthchecks_off is 0\n      ), \"state_value\", \"0\", \"state\", \"healthchecks_off\"\n      # unhealthy is negative number\n    ), \"state_value\", \"-1\", \"state\", \"(dns_error|unhealthy)\"\n  )\n)\nby (job, route, upstream, target, address, state, state_value) > 0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Latency ($job)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(kong_upstream_latency_ms_bucket{job=~\"$job\", service=~\"$service\", route=~\"$route\"}[5m]))",
     "legendFormat": "Upstream Latency - {{service}} - {{route}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nginx Connection State ($instance)",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "repeat": "instance",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kong_nginx_connections_total{state=~\"total|accepted|active|reading|writing|waiting\", instance=~\"$instance\"}) by (job, instance, service, state, subsystem)",
       "legendFormat": "{{job}} - {{state}}"
      }
     ]
    },
    {
     "title": "Kong shared memory usage by Node ($instance) ($job)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kong_memory_lua_shared_dict_bytes{instance=~\"$instance\",shared_dict!~\"kong_process_events\"}/kong_memory_lua_shared_dict_total_bytes{instance=~\"$instance\",shared_dict!~\"kong_process_events\"})*100",
       "legendFormat": "{{shared_dict}} ({{kong_subsystem}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth by Route and Direction Ingress",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(kong_bandwidth_bytes{service=~\"$service\", direction=\"ingress\"}[5m])) by (service)",
       "legendFormat": "{{service}} - Ingress - {{route}}"
      }
     ]
    },
    {
     "title": "Bandwidth by Route and Direction Egress",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kong_bandwidth_bytes{service=~\"$service\", route=~\"$route\", direction=\"egress\"}[5m])",
       "legendFormat": "{{service}} - Egress - {{route}}"
      }
     ]
    },
    {
     "title": "Total Bandwidth ($job)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(kong_bandwidth_bytes{instance=~\"$instance\", job=~\"$job\", service=~\"$service\", route=~\"$route\", route=~\"$route\"}[1m])) by (instance, job, service, route, direction)",
       "legendFormat": " {{route }} - {{direction}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total requests per second (RPS) ($job)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(service, route) (rate(kong_http_requests_total{job=~\"$job\", service=~\"$service\", route=~\"$route\"}[1m]))",
       "legendFormat": "{{service}} - {{route}} - Requests/second"
      }
     ]
    },
    {
     "title": "HTTP Requests by Route and Status Code = 2*",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kong_http_requests_total{job=~\"$job\", service=~\"$service\", route=~\"$route\", code=~\"2.*\"}[5m])",
       "legendFormat": "{{service}} - {{route}} - {{code}}"
      }
     ]
    },
    {
     "title": "HTTP Requests by Route and Status Code = 3**",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 7 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kong_http_requests_total{job=~\"$job\", service=~\"$service\", route=~\"$route\", code=~\"3.*\"}[5m])",
       "legendFormat": "{{service}} - {{route}} - {{code}}"
      }
     ]
    },
    {
     "title": "HTTP Requests by Route and Status Code = 4**",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 7 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kong_http_requests_total{job=~\"$job\", service=~\"$service\", route=~\"$route\", code=~\"4.*\"}[5m])",
       "legendFormat": "{{service}} - {{route}} - {{code}}"
      }
     ]
    },
    {
     "title": "HTTP Requests by Route and Status Code = 5**",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kong_http_requests_total{job=~\"$job\", service=~\"$service\", route=~\"$route\", code=~\"5.*\"}[5m])",
       "legendFormat": "{{service}} - {{route}} - {{code}}"
      }
     ]
    },
    {
     "title": "Kong Latency ($job)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(kong_kong_latency_ms_bucket{job=~\"$job\", service=~\"$service\", route=~\"$route\"}[5m]))",
       "legendFormat": "Kong Latency - {{service}} - {{route}}"
      }
     ]
    },
    {
     "title": "Request Latency ($job)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(kong_request_latency_ms_bucket{job=~\"$job\", service=~\"$service\", route=~\"$route\"}[5m]))",
       "legendFormat": "Request Latency - {{service}} - {{route}}"
      }
     ]
    }
   ]
  }
 ]
}